### ISSUE TITLE
[interactionCommand] DiscordAPIError: Cannot send messages to this user

### ISSUE THREAD

**Issue by HealthScreeningBot-Github** [HealthScreening/HealthScreeningBot#134]
# Error Details
- Error Type: **interactionCommand**
- Error Name: **DiscordAPIError**
- Error Message: **Cannot send messages to this user**
- Error Occured At: **Thursday, December 16, 2021, 10:43:31 PM Eastern Standard Time**

## Error Stack Trace

```
DiscordAPIError: Cannot send messages to this user
    at RequestHandler.execute (/home/aoyansarkar/HealthScreeningBot/node_modules/discord.js/src/rest/RequestHandler.js:349:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/aoyansarkar/HealthScreeningBot/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at async DMChannel.send (/home/aoyansarkar/HealthScreeningBot/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:172:15)
    at async Object.execute (/home/aoyansarkar/HealthScreeningBot/src/commands/setAuto.js:71:9)
    at async HealthScreeningBotClient.oninteractionCreate (/home/aoyansarkar/HealthScreeningBot/src/client/extraClient.js:108:17)
```

## Error Metadata

```json
{
    "redacted": true
}
```

# Issue Details
- Posted By: **@PythonCoderAS**
- Posted At: **Thursday, December 16, 2021, 10:47:44 PM Eastern Standard Time**

**Comment by thunder-red-star** [comment]
The user might have forgot to set their DMs open to the bot...

**Comment by PythonCoderAS** [comment]
> The user might have forgot to set their DMs open to the bot...

You're right. Unlike the other errors where I can deal with it, I am going to have to make an exception here.
