### ISSUE TITLE
ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by PythonCoderAS** [HealthScreening/HealthScreeningBot#162]
```
/Users/aoyansarkar/WebstormProjects/HealthScreeningBot/node_modules/@healthscreening/complete-screening/completeScreening.js:20
const object_to_wrapper_1 = require("@healthscreening/object-to-wrapper");
                            ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/aoyansarkar/WebstormProjects/HealthScreeningBot/node_modules/@healthscreening/object-to-wrapper/objectToWrapper.js from /Users/aoyansarkar/WebstormProjects/HealthScreeningBot/node_modules/@healthscreening/complete-screening/completeScreening.js not supported.
Instead change the require of objectToWrapper.js in /Users/aoyansarkar/WebstormProjects/HealthScreeningBot/node_modules/@healthscreening/complete-screening/completeScreening.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/aoyansarkar/WebstormProjects/HealthScreeningBot/node_modules/@healthscreening/complete-screening/completeScreening.js:20:29)
    at Object.<anonymous> (/Users/aoyansarkar/WebstormProjects/HealthScreeningBot/src/utils/produceScreenshot.js:8:46)
    at Object.<anonymous> (/Users/aoyansarkar/WebstormProjects/HealthScreeningBot/src/screeningClient/processScreening/generateAndSendScreenshot.js:23:29)
    at Object.<anonymous> (/Users/aoyansarkar/WebstormProjects/HealthScreeningBot/src/screeningClient/processScreening/index.js:7:53)
    at Object.<anonymous> (/Users/aoyansarkar/WebstormProjects/HealthScreeningBot/src/screeningClient/index.js:25:44)
    at Object.<anonymous> (/Users/aoyansarkar/WebstormProjects/HealthScreeningBot/src/client/extraClient.js:23:27)
    at Object.<anonymous> (/Users/aoyansarkar/WebstormProjects/HealthScreeningBot/src/client.js:24:39) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v17.2.0
```

**Comment by PythonCoderAS** [comment]
Fixed in #164
