### ISSUE TITLE
[interactionCommand] SequelizeUniqueConstraintError: Validation error

### ISSUE THREAD

**Issue by HealthScreeningBot-Github** [HealthScreening/HealthScreeningBot#196]
# Error Details
- Error Type: **interactionCommand**
- Error Name: **SequelizeUniqueConstraintError**
- Error Message: **Validation error**
- Error Occured At: **Sunday, December 19, 2021, 5:34:08 PM Eastern Standard Time**

## Error Stack Trace

```
Error
    at Query.run (/home/aoyansarkar/HealthScreeningBot/node_modules/sequelize/dist/lib/dialects/postgres/query.js:50:25)
    at /home/aoyansarkar/HealthScreeningBot/node_modules/sequelize/dist/lib/sequelize.js:313:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PostgresQueryInterface.insert (/home/aoyansarkar/HealthScreeningBot/node_modules/sequelize/dist/lib/dialects/abstract/query-interface.js:291:21)
    at async AutoDays.save (/home/aoyansarkar/HealthScreeningBot/node_modules/sequelize/dist/lib/model.js:2400:35)
    at async Function.create (/home/aoyansarkar/HealthScreeningBot/node_modules/sequelize/dist/lib/model.js:1312:12)
    at async Object.execute (/home/aoyansarkar/HealthScreeningBot/src/commands/setAuto.js:62:9)
    at async HealthScreeningBotClient.oninteractionCreate (/home/aoyansarkar/HealthScreeningBot/src/client/extraClient.js:110:17)
```

## Error Metadata

```json
{
    "redacted": true
}
```

# Issue Details
- Posted By: **@PythonCoderAS**
- Posted At: **Sunday, December 19, 2021, 10:22:18 PM Eastern Standard Time**

**Comment by PythonCoderAS** [comment]
Look into https://sequelize.org/master/class/lib/errors/validation-error.ts~ValidationError.html
