### ISSUE TITLE
[root] Error: Failed to launch the browser process!
/home/aoyansarkar/HealthScreeningBot/node_modules/puppeteer/.local-chromium/linux-938248/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md


### ISSUE THREAD

**Issue by HealthScreeningBot-Github** [HealthScreening/HealthScreeningBot#237]
# Error Details
- Error Type: **root**
- Error Name: **Error**
- Error Message: **Failed to launch the browser process!
/home/aoyansarkar/HealthScreeningBot/node_modules/puppeteer/.local-chromium/linux-938248/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory**

  **TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md**
- Error Occured At: **Friday, December 24, 2021, 6:23:29 PM Eastern Standard Time**

## Error Stack Trace

```
Error: Failed to launch the browser process!
/home/aoyansarkar/HealthScreeningBot/node_modules/puppeteer/.local-chromium/linux-938248/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/aoyansarkar/HealthScreeningBot/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:229:20)
    at Interface.<anonymous> (/home/aoyansarkar/HealthScreeningBot/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:219:68)
    at Interface.emit (node:events:402:35)
    at Interface.close (node:internal/readline/interface:496:10)
    at Socket.onend (node:internal/readline/interface:229:10)
    at Socket.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

## Error Metadata

```json
{}
```

# Issue Details
- Posted By: **@PythonCoderAS**
- Posted At: **Friday, December 24, 2021, 6:28:43 PM Eastern Standard Time**

**Comment by PythonCoderAS** [comment]
Fixed by following https://github.com/puppeteer/puppeteer/issues/290
