### ISSUE TITLE
[interaction::commandInteractionAutocomplete::commandDoesNotSupportAutocomplete] Error: Command error log view does not support autocomplete for field avd

### ISSUE THREAD

**Issue by HealthScreeningBot-Github** [HealthScreening/HealthScreeningBot#254]
# Error Details
- Error Type: **interaction::commandInteractionAutocomplete::commandDoesNotSupportAutocomplete**
- Error Name: **Error**
- Error Message: **Command error log view does not support autocomplete for field avd**
- Error Occured At: **Friday, December 24, 2021, 9:54:15 PM Eastern Standard Time**

## Error Stack Trace

```
Error: Command error log view does not support autocomplete for field avd
    at commandInteractionAutocomplete (/Users/aoyansarkar/WebstormProjects/HealthScreeningBot/src/client/interactions/commandInteractionAutocomplete.js:23:43)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async HealthScreeningBotClient.oninteractionCreate (/Users/aoyansarkar/WebstormProjects/HealthScreeningBot/src/client/extraClient.js:125:28)
```

## Error Metadata

```json
{
    "interaction": {
        "user": "199605025914224641",
        "guild": "919616827338924042",
        "channel": "919616827338924045",
        "command": {
            "base": "error",
            "subcommand": "view",
            "subcommandGroup": "log"
        },
        "arguments": [
            {
                "name": "log",
                "type": "SUB_COMMAND_GROUP"
            }
        ]
    },
    "supportedAutocompleteFields": [
        "type_starts_with"
    ]
}
```

# Issue Details
- Posted By: **@PythonCoderAS**
- Posted At: **Friday, December 24, 2021, 9:54:27 PM Eastern Standard Time**

**Comment by PythonCoderAS** [comment]
Fixed in #261
