### ISSUE TITLE
[interaction::commandInteractionAutocomplete] SequelizeDatabaseError: column ErrorLog.id::varchar(255) does not exist

### ISSUE THREAD

**Issue by HealthScreeningBot-Github** [HealthScreening/HealthScreeningBot#256]
# Error Details
- Error Type: **interaction::commandInteractionAutocomplete**
- Error Name: **SequelizeDatabaseError**
- Error Message: **column ErrorLog.id::varchar(255) does not exist**
- Error Occured At: **Friday, December 24, 2021, 10:39:56 PM Eastern Standard Time**

## Error Stack Trace

```
Error
    at Query.run (/Users/aoyansarkar/WebstormProjects/HealthScreeningBot/node_modules/sequelize/dist/lib/dialects/postgres/query.js:50:25)
    at /Users/aoyansarkar/WebstormProjects/HealthScreeningBot/node_modules/sequelize/dist/lib/sequelize.js:313:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PostgresQueryInterface.select (/Users/aoyansarkar/WebstormProjects/HealthScreeningBot/node_modules/sequelize/dist/lib/dialects/abstract/query-interface.js:396:12)
    at async Function.findAll (/Users/aoyansarkar/WebstormProjects/HealthScreeningBot/node_modules/sequelize/dist/lib/model.js:1102:21)
    at async beforeAutocomplete (/Users/aoyansarkar/WebstormProjects/HealthScreeningBot/src/commands/error/log/view/autocomplete/before.js:40:32)
    at async commandInteractionAutocomplete (/Users/aoyansarkar/WebstormProjects/HealthScreeningBot/src/client/interactions/commandInteractionAutocomplete.js:32:17)
    at async HealthScreeningBotClient.oninteractionCreate (/Users/aoyansarkar/WebstormProjects/HealthScreeningBot/src/client/extraClient.js:125:28)
```

## Error Metadata

```json
{
    "user": "199605025914224641",
    "guild": "919616827338924042",
    "channel": "919616827338924045",
    "command": {
        "base": "error",
        "subcommand": "view",
        "subcommandGroup": "log"
    },
    "arguments": [
        {
            "name": "log",
            "type": "SUB_COMMAND_GROUP"
        }
    ]
}
```

# Issue Details
- Posted By: **@PythonCoderAS**
- Posted At: **Friday, December 24, 2021, 10:40:11 PM Eastern Standard Time**

**Comment by PythonCoderAS** [comment]
Fixed in #261
