### ISSUE TITLE
[interaction::commandInteraction] DiscordAPIError: Invalid Form Body
data.embeds[2].description: Must be 4096 or fewer in length.

### ISSUE THREAD

**Issue by HealthScreeningBot-Github** [HealthScreening/HealthScreeningBot#258]
# Error Details
- Error Type: **interaction::commandInteraction**
- Error Name: **DiscordAPIError**
- Error Message: **Invalid Form Body
data.embeds[2].description: Must be 4096 or fewer in length.**
- Error Occured At: **Friday, December 24, 2021, 11:52:43 PM Eastern Standard Time**

## Error Stack Trace

```
DiscordAPIError: Invalid Form Body
data.embeds[2].description: Must be 4096 or fewer in length.
    at RequestHandler.execute (/Users/aoyansarkar/WebstormProjects/HealthScreeningBot/node_modules/discord.js/src/rest/RequestHandler.js:349:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/Users/aoyansarkar/WebstormProjects/HealthScreeningBot/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at async CommandInteraction.reply (/Users/aoyansarkar/WebstormProjects/HealthScreeningBot/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:98:5)
    at async ErrorViewCommand.execute (/Users/aoyansarkar/WebstormProjects/HealthScreeningBot/src/commands/error/view.js:86:16)
    at async commandInteraction (/Users/aoyansarkar/WebstormProjects/HealthScreeningBot/src/client/interactions/commandInteraction.js:29:13)
    at async HealthScreeningBotClient.oninteractionCreate (/Users/aoyansarkar/WebstormProjects/HealthScreeningBot/src/client/extraClient.js:123:28)
```

## Error Metadata

```json
{
    "user": "199605025914224641",
    "guild": "919616827338924042",
    "channel": "919616827338924045",
    "command": {
        "base": "error",
        "subcommand": "view",
        "subcommandGroup": null
    },
    "arguments": [
        {
            "name": "view",
            "type": "SUB_COMMAND"
        }
    ]
}
```

# Issue Details
- Posted By: **@PythonCoderAS**
- Posted At: **Friday, December 24, 2021, 11:54:31 PM Eastern Standard Time**

**Comment by PythonCoderAS** [comment]
Fixed in #261
