### ISSUE TITLE
[interaction::commandInteractionAutocomplete::commandDoesNotSupportAutocomplete] Error: Command set does not support autocomplete for field minute

### ISSUE THREAD

**Issue by HealthScreeningBot-Github** [HealthScreening/HealthScreeningBot#508]
# Error Details
- Error ID: **631**
- Error Type: **interaction::commandInteractionAutocomplete::commandDoesNotSupportAutocomplete**
- Error Name: **Error**
- Error Message: **Command set does not support autocomplete for field minute**
- Error Occured At: **Wednesday, January 12, 2022, 3:08:56 PM Eastern Standard Time**

## Error Stack Trace

```
Error: Command set does not support autocomplete for field minute
    at commandInteractionAutocomplete (/home/aoyansarkar/HealthScreeningBot/src/client/interactions/commandInteractionAutocomplete.js:23:43)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async HealthScreeningBotClient.oninteractionCreate (/home/aoyansarkar/HealthScreeningBot/src/client/extraClient.js:139:28)
```

## Error Metadata

```json
{
    "interaction": {
        "user": "199605025914224641",
        "guild": "889983763994521610",
        "channel": "899314875610824725",
        "command": {
            "base": "set",
            "subcommand": null,
            "subcommandGroup": null
        },
        "arguments": [
            {
                "name": "minute",
                "type": "INTEGER",
                "value": "35",
                "focused": true
            }
        ]
    },
    "supportedAutocompleteFields": [
        "device"
    ]
}
```

# Issue Details
- Posted By: **@PythonCoderAS**
- Posted At: **Sunday, January 16, 2022, 6:56:08 PM Eastern Standard Time**

**Comment by PythonCoderAS** [comment]
The fix has been deployed previously.
