### ISSUE TITLE
[doAutoLoop] SequelizeDatabaseError: cache lookup failed for function 33554782

### ISSUE THREAD

**Issue by HealthScreeningBot-Github** [HealthScreening/HealthScreeningBot#649]
# Error Details
- Error ID: **1077**
- Error Type: **doAutoLoop**
- Error Name: **SequelizeDatabaseError**
- Error Message: **cache lookup failed for function 33554782**
- Error Occured At: **Monday, March 28, 2022, 7:10:00 AM Eastern Daylight Time**

## Error Stack Trace

```
Error
    at Query.run (/home/aoyansarkar/HealthScreeningBot/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)
    at /home/aoyansarkar/HealthScreeningBot/node_modules/sequelize/lib/sequelize.js:313:28
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PostgresQueryInterface.select (/home/aoyansarkar/HealthScreeningBot/node_modules/sequelize/lib/dialects/abstract/query-interface.js:396:12)
    at async Function.findAll (/home/aoyansarkar/HealthScreeningBot/node_modules/sequelize/lib/model.js:1119:21)
    at async doAutoLoop (/home/aoyansarkar/HealthScreeningBot/src/client/doAutoLoop.js:23:32)
```

## Error Metadata

```json
{
    "time": {
        "hour": 7,
        "minute": 10,
        "weekday": 1
    },
    "logChannel": "902375187150934037"
}
```

# Issue Details
- Posted By: **@PythonCoderAS**
- Posted At: **Monday, March 28, 2022, 10:28:26 PM Eastern Daylight Time**

**Comment by PythonCoderAS** [comment]
Fixed.
