### ISSUE TITLE
[root] Error: Failed to launch the browser process!
/home/pi/HealthScreeningBot/node_modules/puppeteer/.local-chromium/linux-970485/chrome-linux/chrome: 1: /home/pi/HealthScreeningBot/node_modules/puppeteer/.local-chromium/linux-970485/chrome-linux/chrome:

### ISSUE THREAD

**Issue by HealthScreeningBot-Github** [HealthScreening/HealthScreeningBot#650]
# Error Details
- Error ID: **1078**
- Error Type: **root**
- Error Name: **Error**
- Error Message: **Failed to launch the browser process!
/home/pi/HealthScreeningBot/node_modules/puppeteer/.local-chromium/linux-970485/chrome-linux/chrome: 1: /home/pi/HealthScreeningBot/node_modules/puppeteer/.local-chromium/linux-970485/chrome-linux/chrome: Syntax error: redirection unexpected

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
**
- Error Occured At: **Monday, March 28, 2022, 10:24:07 PM Eastern Daylight Time**

## Error Stack Trace

```
Error: Failed to launch the browser process!
/home/pi/HealthScreeningBot/node_modules/puppeteer/.local-chromium/linux-970485/chrome-linux/chrome: 1: /home/pi/HealthScreeningBot/node_modules/puppeteer/.local-chromium/linux-970485/chrome-linux/chrome: Syntax error: redirection unexpected


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/pi/HealthScreeningBot/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:237:20)
    at Interface.<anonymous> (/home/pi/HealthScreeningBot/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:227:68)
    at Interface.emit (node:events:532:35)
    at Interface.close (node:readline:586:8)
    at Socket.onend (node:readline:277:10)
    at Socket.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1346:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

## Error Metadata

```json
{}
```

# Issue Details
- Posted By: **@PythonCoderAS**
- Posted At: **Monday, March 28, 2022, 10:28:32 PM Eastern Daylight Time**

**Comment by PythonCoderAS** [comment]
Fixed.
