### ISSUE TITLE
[root] ProtocolError: Protocol error (Target.setDiscoverTargets): Target closed.

### ISSUE THREAD

**Issue by HealthScreeningBot-Github** [HealthScreening/HealthScreeningBot#695]
# Error Details
- Error ID: **1105**
- Error Type: **root**
- Error Name: **ProtocolError**
- Error Message: **Protocol error (Target.setDiscoverTargets): Target closed.**
- Error Occured At: **Tuesday, April 26, 2022, 4:15:23 PM Eastern Daylight Time**

## Error Stack Trace

```
ProtocolError: Protocol error (Target.setDiscoverTargets): Target closed.
    at /home/aoyansarkar/HealthScreeningBot/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:75:24
    at new Promise (<anonymous>)
    at Connection.send (/home/aoyansarkar/HealthScreeningBot/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:71:16)
    at Function.create (/home/aoyansarkar/HealthScreeningBot/node_modules/puppeteer/lib/cjs/puppeteer/common/Browser.js:121:26)
    at ChromeLauncher.launch (/home/aoyansarkar/HealthScreeningBot/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:129:50)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async startupBrowser (/home/aoyansarkar/HealthScreeningBot/node_modules/@healthscreening/generate-screenshot/generateScreenshot.js:29:27)
    at async startup (/home/aoyansarkar/HealthScreeningBot/src/client.js:39:9)
```

## Error Metadata

```json
{}
```

# Issue Details
- Posted By: **@PythonCoderAS**
- Posted At: **Thursday, April 28, 2022, 10:26:57 AM Eastern Daylight Time**

**Comment by PythonCoderAS** [comment]
Theorized to be a faulty server.
