### ISSUE TITLE
[doAutoLoop] SequelizeDatabaseError: column "nan" does not exist

### ISSUE THREAD

**Issue by HealthScreeningBot-Github** [HealthScreening/HealthScreeningBot#696]
# Error Details
- Error ID: **1106**
- Error Type: **doAutoLoop**
- Error Name: **SequelizeDatabaseError**
- Error Message: **column "nan" does not exist**
- Error Occured At: **Tuesday, April 26, 2022, 6:54:00 PM Eastern Daylight Time**

## Error Stack Trace

```
Error
    at Query.run (/home/aoyansarkar/HealthScreeningBot/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)
    at /home/aoyansarkar/HealthScreeningBot/node_modules/sequelize/lib/sequelize.js:313:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PostgresQueryInterface.select (/home/aoyansarkar/HealthScreeningBot/node_modules/sequelize/lib/dialects/abstract/query-interface.js:396:12)
    at async Function.findAll (/home/aoyansarkar/HealthScreeningBot/node_modules/sequelize/lib/model.js:1119:21)
    at async doAutoLoop (/home/aoyansarkar/HealthScreeningBot/src/client/doAutoLoop.js:23:32)
```

## Error Metadata

```json
{
    "time": {
        "hour": null,
        "minute": null,
        "weekday": null
    },
    "logChannel": "902375187150934037"
}
```

# Issue Details
- Posted By: **@PythonCoderAS**
- Posted At: **Thursday, April 28, 2022, 10:27:02 AM Eastern Daylight Time**

**Comment by PythonCoderAS** [comment]
Theorized to be a faulty server.
