### ISSUE TITLE
[interaction::commandInteraction] Error: Invalid weekday: NaN

### ISSUE THREAD

**Issue by HealthScreeningBot-Github** [HealthScreening/HealthScreeningBot#842]
# Error Details
- Error ID: **1413**
- Error Type: **interaction::commandInteraction**
- Error Name: **Error**
- Error Message: **Invalid weekday: NaN**
- Error Occured At: **Wednesday, July 20, 2022 at 3:22:44 PM Eastern Daylight Time**

## Error Stack Trace

```
Error: Invalid weekday: NaN
    at TestScreening.execute (/home/aoyansarkar/HealthScreeningBot/src/commands/testScreening.js:98:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async commandInteraction (/home/aoyansarkar/HealthScreeningBot/src/client/interactions/commandInteraction.js:41:13)
    at async HealthScreeningBotClient.oninteractionCreate (/home/aoyansarkar/HealthScreeningBot/src/client/extraClient.js:122:21)
```

## Error Metadata

```json
{
    "user": "199605025914224641",
    "guild": "889983763994521610",
    "channel": "903064552772620339",
    "command": {
        "base": "test_screening",
        "subcommand": null,
        "subcommandGroup": null
    },
    "arguments": [
        {
            "name": "month",
            "type": 4,
            "value": 234
        }
    ]
}
```

# Issue Details
- Posted By: **@PythonCoderAS**
- Posted At: **Wednesday, July 20, 2022 at 3:23:01 PM Eastern Daylight Time**

**Comment by PythonCoderAS** [comment]
Fixed in a recent commit
